# Docker Compose - Produção
# Use: docker-compose -f docker-compose.prod.yml up -d

services:
  app:
    build:
      context: .
      target: production
    image: todolist-backend:prod
    container_name: todolist-app-prod
    ports:
      - '${PORT:-3000}:3000'
    depends_on:
      - mysql
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-root}
      - DB_NAME=${DB_NAME:-todolist_db}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: todolist-mysql-prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-todolist_db}
    ports:
      - '${MYSQL_PORT:-3307}:3306'
    volumes:
      - todolist_mysql_prod_data:/var/lib/mysql

volumes:
  todolist_mysql_prod_data:
